#!/bin/sh
exec 2>&1
source /etc/envvars
echo " ==== starting 'nginx -c /etc/nginx/nginx.conf' "
/usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;" 
if [ $? -ne 0 ]; then
  echo " ==== unable to start 'nginx -c /etc/nginx/nginx.conf' (sleeping 30 seconds) " 
  sleep 30 
fi
